#! /bin/bash
RepoURL="repo"
codename="pbuilder"

#CSV parse
if [ -n "$CSV" ];then
    PBROOT=`echo ${CSV}| awk -F '|' '{print $1}'`
    XAUTH=`echo ${CSV}| awk -F '|' '{print $2}'`
fi

repo_add(){
    cat /etc/apt/sources.list|grep "$repo" >/dev/null 2>&1
    if [ $? -ne 0 ];then
        echo "$repo" >>/etc/apt/sources.list
    fi
}

repo_del(){
    sed -i "/$repo/d" /etc/apt/sources.list
}

# add or remove tmprepo
repo="deb file:/var/cache/pbuilder/tmprepo ${codename} main contrib non-free vega"
if [ -f /var/cache/pbuilder/tmprepo/dists/${codename}/main/binary-amd64/Packages ];then
    repo_add
else
    repo_del
fi
    apt-get update

#bashrc
if [ "$PBROOT" != "$HOME" ];then
    echo "cd $PBROOT">$HOME/.bashrc
fi

# X forvard
# X redirect only from ssh -X
if [ "$XAUTH" != "" ];then
    echo "Start X Display"
    apt-get -y install xauth
    xauth add ${XAUTH}
else
    echo "Start Console mode"
fi
