#! /bin/bash
RepoURL="127.0.0.1"
codename="pbuilder"

repo_add(){
    cat /etc/apt/sources.list|grep "$repo" >/dev/null 2>&1
    if [ $? -ne 0 ];then
        echo "$repo" >>/etc/apt/sources.list
    fi
}

repo_del(){
    sed -i "/$repo/d" /etc/apt/sources.list
}

#add pod repo
#repo="deb ftp://${RepoURL}/vega astra14_gst10 main contrib non-free vega"
#repo_add
#repo="deb ftp://${RepoURL}/vega astra14_qgis main contrib non-free vega"
#repo_add
#repo="deb ftp://${RepoURL}/vega astra14_training main contrib non-free vega"
#repo_add

# add or remove tmprepo
repo="deb file:/var/cache/pbuilder/tmprepo ${codename} main contrib non-free vega"
if [ -f /var/cache/pbuilder/tmprepo/dists/${codename}/main/binary-amd64/Packages ];then
    repo_add
else
    repo_del
fi
    apt-get update
