#!/bin/bash

. /etc/pb.cfg

#init version
if [ -n "$1" ];then
    if [ -f "/etc/pbuilderrc.$1" ];then
        . /etc/pbuilderrc.$1
    else
        echo "Config file /etc/pbuilderrc.$1 not found"
        exit 1
    fi
else
    echo "Please insert init version"
    exit 1
fi

#copy base tgz
if [ -f "$BASETGZ" ];then
    if [ -f $tgz_name ];then
        sudo env HOME=/root rm $tgz_name
    else
        sudo env HOME=/root mkdir -p `dirname ${tgz_name}`
    fi
    sudo env HOME=/root cp ${BASETGZ} ${tgz_name}
else
    echo "Please start \"pbuilder create --configfile /etc/pbuilderrc.$1\" from superuser"
fi

