#!/bin/bash

. /etc/pb.cfg

if [ ! -f $tgz_name ];then
    echo "Please rum \"pdinit\" from current directory"
    exit 1
fi

# create csv
if [ -n "$DISPLAY" ];then
    XAUTH=`xauth list $DISPLAY`
else
    XAUTH=""
fi
CSV=$(echo "$PBROOT" && echo "|" && echo "$XAUTH")

sudo env CSV="$CSV" /usr/sbin/pbuilder login --basetgz $tgz_name --bindmounts $PBROOT --save-after-login $@

#useername directory correct from user
for user_dir in $user_dirs
do
    echo $PBROOT|grep ${user_dir} >/dev/null 2>&1
    if [ $? -eq 0 ];then
        sudo env HOME=/root chown --reference=$PBROOT -R $PBROOT
    fi
done

exit 0

