#!/bin/bash

. /etc/pb.cfg

if [ ! -f $tgz_name ];then
    echo "Please rum \"pdinit\" from current directory"
    exit 1
fi

# create script dir
mkdir -m 777 -p /tmp/pb

# name temp files
sname=/tmp/pb/$(basename $tgz_name)_$(date +%s).sh
errname=$PBROOT/\.$(basename $tgz_name)_$(date +%s).err

# create run script
echo "echo ----------------------">${sname}
echo "cd $PBROOT">>${sname}
if [ -n "$1" ];then
    echo "$@">>${sname}
fi
if [ ! -t 0 ];then
    while read -r line; do
        echo "$line">>${sname}
    done
fi
echo "echo \$? >${errname}">>${sname}
echo "echo ----------------------">>${sname}

#create CSV
if [ -n "$DISPLAY" ];then
    XAUTH=`xauth list $DISPLAY`
else
    XAUTH=""
fi
CSV=$(echo "$PBROOT" && echo "|" && echo "$XAUTH")

# test teamcity build directory and chmod content
echo $PBROOT|grep ${tc_root_dir} >/dev/null 2>&1
if [ $? -eq 0 ];then
    echo "USE:\"${PBROOT}\" directory from Teamcity build agent"
    sudo env CSV="$CSV" /usr/sbin/pbuilder execute --basetgz $tgz_name --bindmounts $PBROOT -- ${sname}
    # username directory correct from user teamcity_agent
    sudo env HOME=/root chown --reference=$PBROOT -R $PBROOT
else
    echo "USE:\"${PBROOT}\" directory from manual build"
    sudo env CSV="$CSV" /usr/sbin/pbuilder execute --basetgz $tgz_name --bindmounts $PBROOT --save-after-exec -- ${sname}
    # username directory correct from user user
    for user_dir in $user_dirs
    do
        echo $PBROOT|grep ${user_dir} >/dev/null 2>&1
        if [ $? -eq 0 ];then
            sudo env HOME=/root chown --reference=$PBROOT -R $PBROOT
        fi
    done
fi

# finalisy
errcode=`cat ${errname}`
rm ${sname}
rm -f ${errname}

exit ${errcode}
