#!/bin/bash

#init version
if [ -n "$1" ];then
    if [ -f "/etc/pbuilderrc.$1" ];then
        CONFIGFILE="/etc/pbuilderrc.$1"
    else
        echo "ERROR: Config file /etc/pbuilderrc.$1 not found"
        exit 1
    fi
else
    echo "ERROR: Please enter init version"
    exit 1
fi

CMD=`echo $@ |awk -F ' ' '{for(i=1;i<=NF;i++) {printf(" "); if(i>1) {printf($i);}}}'`

sudo pbuilder ${CMD} --configfile ${CONFIGFILE}